default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  username: postgres
  password: Waithira2013 

development:
  <<: *default
  database: Blog_app_development

test:
  <<: *default
  database: Blog_app_test

production:
  <<: *default
  database: Blog_app_production
